### ISSUE TITLE
Segmentation Fault (core dumped) causes many containers to be stuck in restart loop

### ISSUE THREAD

**Issue by sanoel** [OADA/oada-srvc-docker#14]
After running `docker-compose up -d`, `docker-compose ps` reveals that most of the containers have a state of "Restarting". Upon further inspection in the logs, the containers end in a segmentation fault: 
```http-handler           | > oada-srvc-http-handler@1.0.0 start /code/http-handler/oada-srvc-http-handler
http-handler           | > CONTAINER_NAME="HTTP Handler" node server.js "--config=/oada-srvc-docker-config.js"
http-handler           | 
http-handler           | Segmentation fault (core dumped)
http-handler           | npm ERR! code ELIFECYCLE
http-handler           | npm ERR! errno 139
http-handler           | npm ERR! oada-srvc-http-handler@1.0.0 start: `CONTAINER_NAME="HTTP Handler" node server.js "--config=/oada-srvc-docker-config.js"`
http-handler           | npm ERR! Exit status 139
http-handler           | npm ERR! 
http-handler           | npm ERR! Failed at the oada-srvc-http-handler@1.0.0 start script.
http-handler           | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
http-handler           | 
http-handler           | npm ERR! A complete log of this run can be found in:
http-handler           | npm ERR!     /root/.npm/_logs/2018-11-28T02_35_39_816Z-debug.log
```

**Comment by abalmos** [comment]
Try with a more modern node? 10.14 is LTS, 11.3 is current. Looks like it is currently using 8.7 https://github.com/OADA/oada-srvc-docker/blob/52e781d3a45806c39dd161f1e9c4cef73b6fb6bb/http-handler/Dockerfile#L1

If that doesn't help then I guess I would first look into packages that compile a dependency. I think the encryption related packages might.

**Comment by sanoel** [comment]
I'll give it a try. I thought we ran into some other bizarre issues with node-rdkafka once we started upgrading node.

**Comment by abalmos** [comment]
`node-rdkafka` also compiles a c lib (so I recall). Maybe that has something to do with it? I assume upgrading node will also upgraded Alpine Linux. Could be a system level library issue with the newer Alpine.

**Comment by sanoel** [comment]
The version of librdkafka being used by a dependency seemed to be the source of the issue. `node-rdkafk` only works with librdkafka 0.11.5 while 0.11.6 was getting used. Using node-rdkafka v2.3.0 along with a docker image for node 8 (we used node:8-alpine) got things back in working order. Furthermore, pushing docker images of working builds to dockerhub is also on the roadmap and should resolve these types of issues in the future.
