### ISSUE TITLE
deletes need further testing

### ISSUE THREAD

**Issue by sanoel** [OADA/oada-srvc-docker#3]
It may have had to do with the bug regarding PUTs unexpectedly going to parent resources

**Comment by sanoel** [comment]
Deleting links doesn't seem to work.  Currently, it goes and deletes the resource, but not the links. Subsequent GETs on the links return Forbidden (also a bit misleading).

**Comment by awlayton** [comment]
We need to decide if DELETE on a path that is a link removes the link from its parent resource and/or removes the resource pointed to by the link.

It returns forbidden afterwards because the resource the link is pointing to no longer exists.

**Comment by aultac** [comment]
We need to have a way to delete a resource AND a way to delete just a link to a resource.  i.e. maybe I want to delete this link to resource 145, but I don't want to delete resource 145.  I think we can do this if we say that the only way to delete a resource is to delete it's canonical path (i.e. /resources/145).  If you delete a path which only linked to resource 145 then it should just delete the link but leave the resource.  Thoughts?
