### ISSUE TITLE
What happens to _changes on DELETE

### ISSUE THREAD

**Issue by awlayton** [OADA/oada-srvc-docker#36]
Currently when you delete a resource its changes are not deleted. Then if a resource with the same `_id` is created it "inherits" that change feed, but its `_rev` is still 1.

This behavior is unexpected and confusing and understandably breaks oada-cache.

I see two options on how to remedy it:
  1. delete a resource's changes along with it
  2. when a resource "inherits" changes, do not reset its `_rev` to 1 (set it to the next rev according to the change feed instead)

**Comment by awlayton** [comment]
At some point option 2 of this has been implemented.

**Comment by aultac** [comment]
I implemented option #2 awhile ago, but I am not sure it is optimal yet.  I like the fact that a) DELETE can be recovered and b) the change feed is immutable.  Option 2 achieved this.  

However, I think Andrew correctly pointed out at the time that if someone deletes a resource, and then someone else puts again to that same resourceid, then the subsequent put does not have any good means of checking permissions.  i.e. if I didn’t have permission to the resource before, once you delete it, then if I can figure out the resource id (from any user and any domain hosted on the same platform), I can write to it and now I own it with it’s complete change history.

I think the right thing to do is assert that only the “owner” has permission to resurrect a deleted resource.  This means that the “_delete” should probably record the owner in the actual change doc, and then the part of the code that is resuming that change feed later should just check that before allowing the resurrection.  

I also think at some point we’d implement an admin-level script that would allow an admin to “compact” their OADA installation by actually removing those changes from old deleted resources, snapshotting really old change graphs, etc.

Aaron
