### ISSUE TITLE
POSTing a link returns Content-Location of the link

### ISSUE THREAD

**Issue by abalmos** [OADA/oada-srvc-docker#38]
POSTing

``` { "_id": "resources/abc123" }```

to `/bookmarks/trellisfw/documents` returns a content-location of `/resources/abc132` where one would have expected it to be `/resources/<id-of-documents-resources/<new-key-id>`

**Comment by awlayton** [comment]
I am unable to reproduce. I'm assuming this has since been fixed. If you encounter it in v3 please reopen.
