### ISSUE TITLE
What to return on a PUT/POST

### ISSUE THREAD

**Issue by abalmos** [OADA/oada-srvc-docker#39]
We need to decide how to properly handle this commit: 77be9f425964fde18e010c311c8c06c04935fe92

We should return 200 / 201 / 204 ... `Location` header is no longer sent, should it be?

Note: This change was because the `.redirect()` was causing to response to have a non-zero content-length, making axios/fetch/etc. blocking forever waiting for a response that was never coming.

**Comment by awlayton** [comment]
We use the `Content-Location` header on PUT/POST responses now.
