### ISSUE TITLE
auth continually crashes on Windows host

### ISSUE THREAD

**Issue by awlayton** [OADA/oada-srvc-docker#43]
When docker is running in Windows, the auth docker does not run.

**Comment by aultac** [comment]
What does it do (i.e. what are the logs), and who’s running it in windows?

**Comment by awlayton** [comment]
Part of the issue was `URIjs` changing its name to `urijs`, which I have pushed a fix for to #33. This created issues because NTFS is not case sensitive.

The remaining issue is that the symlinks are not understood by windows (e.g., it breaks trying to follow the link from `domains-enabled/localhost` to `domains-available/localhost`).

**Comment by awlayton** [comment]
I figured out the [symlink thing](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#YeBCd1HJ6c6rlqBv.97). The tl;dr is you have to enable "Developer Mode" for symlinks to work in Windows for some reason. 🤷‍♂ 

So we can call this issue closed when the changes from #33 get merged in.

**Comment by awlayton** [comment]
Fixed by merge of #33
